name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      - name: Run Tests
        run: echo "Tests would run here!"

      - name: Deploy Application
        run: echo "Deploy commands would run here!"
